### PR TITLE
Fix/update gatsby

### LINKED ISSUE #47: Update Gatsby packages
This will be a major version update from 2 to 3, please see migration guide:
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/

`gatsby-image` has been deprecated and should be replaced by `gatsby-plugin-image`:
https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide/

`gatsby-source-contentful` changes:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/CHANGELOG.md#400-next0-2020-11-09

### PR DESCRIPTION
**Pull request by idosius**
Based on work by @Arskah and then some:

- Update `gatsby*` packages to latest versions
- Migrate `gatsby-image` to `gatsby-plugin-image`
  - Run codmod to replace components accordingly
  - Update GQL queries to use for `gatsbyImageData` rather than `fluid`
  - Add custom image breakpoints and layout where necessary
- Migrate `gatsby-source-contentful`
  - Refactor `RichText` according to the [release notes](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/CHANGELOG.md#400-next0-2020-11-09) + no need to serialize data + `fields` prop no longer supported
  - Update GQL queries to use `raw` since `json` is no longer supported
  - Update GQL queries to use `references` since they are required to fully resolve assets + embeds
  - Remove extra querying for images + image finding in `RichText` since it isn't required anymore
- Fix env variable from `HUBSPOT_PORTAL_ID` to `GATSBY_HUBSPOT_PORTAL_ID` so that it's available in the app
- Add up to date `eslint` definitions
- Fix certain CSS classNames because they were causing build errors
- Change the order of some imports since they were causing build errors
- Fix `BlogPost` `metaTitle` to use `title` when the former isn't available
- Fix filters that suddenly stopped working

### Known issues

- Can't update to the latest `eslint-webpack-plugin` [because of an issue](https://github.com/webpack-contrib/eslint-webpack-plugin/issues/106)
- For some reason, the below errors are produced when querying for assets and building the website, although they do not seem to hurt any functionality ([opened this issue for the plugin](https://github.com/gatsbyjs/gatsby/issues/32362)):

```
error [gatsby-source-contentful] Could not getDominantColor from image [Error: ENOENT: no such file or directory, open '/home/travis/build/wunderdogsw/w3/.cache/contentful/assets/Screenshot 2020-08-12 at 12.56.01-a2e16a575ab4ea7f4f6df4fe7488d249.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/travis/build/wunderdogsw/w3/.cache/contentful/assets/Screenshot 2020-08-12 at 12.56.01-a2e16a575ab4ea7f4f6df4fe7488d249.png'
}
```

Closes #47

### CODE REVIEW

File: src/templates/case-story.js [hunk 1]
```diff
@@ -64,22 +64,23 @@ const CaseStory = ({ data }) => {
...
         }
       }
       metaTitle
       metaDescription {
         metaDescription
       }
       metaImage {
-        fluid(maxHeight: 1080) {
-          src
+        file {
```
Comment (idosius) [inline src/templates/case-story.js:82]: Make sure to constrain meta image size, full HD

File: src/templates/case-story.js [hunk 2]
```diff
@@ -64,22 +64,23 @@ const CaseStory = ({ data }) => {
...
-  query ($slug: String!, $next: String!, $images: [String!]!) {
+  query ($slug: String!, $next: String!) {
     story: contentfulCaseStory(slug: { eq: $slug }) {
       title
       image {
         title
-        fluid(sizes: "(max-width: 1200px) 400px, 1600px") {
-          ...GatsbyContentfulFluid_withWebp
+        gatsbyImageData(layout: FULL_WIDTH)
+        file {
```
Comment (midori0507) [inline src/templates/case-story.js:73]: This as well

**Review by midori0507 — APPROVED** [review]
