### PR TITLE
fix bug so that menu closes when clicking the current page

### LINKED ISSUE #61: Menu doesn't close when clicking the current page
1. Go to the website
2. Open the toggle menu on the top right
3. Click some link, e.g. Blog
4. The menu will close and the blog page will open
5. Open the menu again
6. Click blog
7. Nothing will happen

Expected behavior: the menu should simply close

### PR DESCRIPTION
**Pull request by idosius**
Fixes #61

### CODE REVIEW

File: src/components/menu.js [hunk 1]
```diff
@@ -33,6 +33,10 @@ const Menu = ({ active }) => {
             key={page.id}
             to={page.fields.route}
             activeClassName={styles.active}
+            onClick={async () => {
```
Comment (midori0507) [inline src/components/menu.js:36]: can you create new function and paste the function in here instead, just better readability

**Review by midori0507 — APPROVED** [review]
